# -*- coding: utf-8 -*-
"""majorproject.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10SU38DeYPXmJHgxSIpBphmJj93L_qe0Y
"""

import random
from textblob import TextBlob

print('Hey there human what is your name?')
name=input()
print('Do you have a nickname?')
ans=input()
if 'y' in ans.lower():
  nickname=input('What is your nickname?')
  print('Its nice to meet you '+ nickname)
if 'n' in ans.lower():
    nickname=name+'preet'
    print('I will call you ' + nickname)

greetings=['How are you '+ nickname +'?',"What's up " + nickname + "?","How's life going on " + nickname + "?",'Howdy '+ nickname + ' how are you feeling?','Greetings '+ nickname +' are you well?']
print(random.choice(greetings))

ans=input()
blob=TextBlob(ans)

if blob.polarity>0:
  print('Glad to hear you are well')
else:
   print('Sorry to hear that')

topics=['Cricket','video games','Delhi','Anime','Shopping','Python','Gym','music','Dance','mirzapur webseries']
questions=['What is your take on ','What do you think about ','How do you feel about ','I would like your opinion about ','So tell me something about ']

for i in range(0,random.randint(3,5)):
    question=random.choice(questions)
    questions.remove(question)
    topic=random.choice(topics)
    topics.remove(topic)
    print(question + topic + '?')
    ans=input()
    blob=TextBlob(ans)

    if blob.polarity>0.5:
      print('OMG you really love '+ topic)
    elif blob.polarity>0.1:
      print('Well you clearly like ' + topic)
    elif blob.polarity<-0.5:
      print('Damn,you totally hate ' + topic)
    elif blob.polarity<-0.1:
      print("Hmm,so you don't like " + topic)
    else:
      print('That is very neutral view on ' + topic)

    if blob.subjectivity>0.6:
      print('you are so biased')
    elif blob.subjectivity>0.3:
      print('you are a bit biased')
    else:
      print('and you are quite objective')

goodbyes=['Good talking to you ' + nickname + ' i gotta go now','Ok i am bored now time to go and watch netflix','Yawwnnn.....feeling dizzy gonna sleep now','oh shit its long gotta go now','Catch ya later ' + nickname ]
print(random.choice(goodbyes))